### ISSUE TITLE
State of gdextension branch?

### ISSUE THREAD

**Issue by fire** [Dheatly23/godot-wasm#1]
What is the state of the gdextension branch?

**Comment by Dheatly23** [comment]
Currently, it is broken mostly due to godot-rust/gdext#138 and godot-rust/gdext#159. Unfortunately, those bugs were on upstream, so progress is blocked.

**Comment by lilizoey** [comment]
the first one of those was fixed actually, as of yesterday.

**Comment by Dheatly23** [comment]
Oh okay then, i'll try it ASAP.

**Comment by Dheatly23** [comment]
After some patches and fixing example, it is **useable**. You should be able to run example project.

NOTE: Many features are not yet implemented:
- [x] Calling any method from host method (common pattern with reading/writing memory) (sort of works, sometimes fail)
- [ ] Auto-unwrap weakref host method (to be replaced with Callable)
- [x] Getter for properties (`name` and `module`)
- [ ] Error signalling and formatting (blocked in upstream)
- [ ] Experimental Godot API
- [x] New features since split (need to rebase)

**Comment by fire** [comment]
https://github.com/ashtonmeuser/godot-wasm is an alternative implementation of Godot Engine 4.0 wasm for GDExtension and C++ module. Linking for the search engines.

**Comment by tjpalmer** [comment]
> https://github.com/ashtonmeuser/godot-wasm is an alternative implementation of Godot Engine 4.0 wasm for GDExtension and C++ module. Linking for the search engines.

How does this project relate to the ashtonmeuser project?

**Comment by Dheatly23** [comment]
> How does this project relate to the ashtonmeuser project?

In short: We both wrote it independently of each other.

Technically i made it first (based on commit history), but got sniped on publishing date.

**Comment by tjpalmer** [comment]
> > How does this project relate to the ashtonmeuser project?
> 
> In short: We both wrote it independently of each other.
> 
> Technically i made it first (based on commit history), but got sniped on publishing date.

Thanks much for the explanation! Maybe I'll try them both out.
